apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret-hafifa-server
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}
